version: '3.9'

services:
  app-dev:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  app-homolog:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    env_file:
      - .env.homolog
    command: node dist/index.js

  app-prod:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    command: node dist/index.js
